# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('code', models.CharField(default='', max_length=5)),
                ('imageURL', models.URLField()),
                ('duration', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('groupSize', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('code', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GenericOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('genericId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Generic')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=5)),
                ('office', models.CharField(default='', max_length=10)),
                ('visitingHours', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('personType', models.IntegerField()),
                ('lastLogined', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='', max_length=1)),
                ('comment', models.CharField(blank=True, default='', max_length=30)),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('lastModified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(default='', max_length=8)),
                ('branch', models.CharField(default='', max_length=5)),
                ('sId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Person')),
            ],
        ),
        migrations.AddField(
            model_name='instrutor',
            name='iId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Person'),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Groups'),
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='sId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Student'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='genericId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Generic'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='rubricId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Rubric'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor'),
        ),
        migrations.AddField(
            model_name='activity',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Course'),
        ),
        migrations.AddField(
            model_name='activity',
            name='rubricId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Rubric'),
        ),
    ]
