# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('code', models.CharField(default='', max_length=5)),
                ('duration', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('groupSize', models.IntegerField(default=1)),
                ('textOrImage', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=5000)),
                ('groupId', models.TextField(blank=True, default='', null=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImageAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileURL', models.CharField(default='', max_length=5000)),
                ('groupId', models.TextField(blank=True, default='', null=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(blank='True', default='', max_length=200)),
                ('code', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('answer', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('optionNo', models.IntegerField(default=0)),
                ('genericId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Generic')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=5)),
                ('office', models.CharField(default='', max_length=10)),
                ('visitingHours', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('personType', models.IntegerField()),
                ('lastLogined', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Course')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredGroupsForActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigmentPk', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='', max_length=1)),
                ('comment', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Criteria')),
                ('registeredGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.RegisteredGroupsForActivity')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('lastModified', models.DateTimeField(auto_now_add=True)),
                ('iId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(default='', max_length=8)),
                ('branch', models.CharField(default='', max_length=5)),
                ('sId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Person')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='p2preview/static/p2preview/files')),
            ],
        ),
        migrations.AddField(
            model_name='registeredcourses',
            name='sId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Student'),
        ),
        migrations.AddField(
            model_name='instrutor',
            name='iId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Person'),
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='sId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Student'),
        ),
        migrations.AddField(
            model_name='generic',
            name='iId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='genericId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Generic'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='rubricId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Rubric'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor'),
        ),
        migrations.AddField(
            model_name='activity',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Course'),
        ),
        migrations.AddField(
            model_name='activity',
            name='iId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor'),
        ),
        migrations.AddField(
            model_name='activity',
            name='rubricId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Rubric'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('registeredGroup', 'criteria')]),
        ),
        migrations.AlterUniqueTogether(
            name='registeredgroupsforactivity',
            unique_together=set([('groupId', 'assigmentPk')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupdetail',
            unique_together=set([('groupId', 'sId')]),
        ),
        migrations.AlterUniqueTogether(
            name='genericoption',
            unique_together=set([('genericId', 'optionNo')]),
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together=set([('rubricId', 'genericId')]),
        ),
    ]
