# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
