# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericoption',
            name='option',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.ImageField(upload_to='static/p2preview/files'),
        ),
    ]
