# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=5000)),
                ('groupId', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('count', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImageAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileURL', models.CharField(default='', max_length=5000)),
                ('count', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GenericOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('optionNo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Course')),
                ('sId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Student')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredGroupsForActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigmentPk', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='p2preview/static/p2preview/files')),
            ],
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupDetails',
            new_name='GroupDetail',
        ),
        migrations.RemoveField(
            model_name='genericoptions',
            name='genericId',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='activity',
            name='iId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='textOrImage',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='criteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2preview.Criteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='iId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generic',
            name='answer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together=set([('rubricId', 'genericId')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupdetail',
            unique_together=set([('groupId', 'sId')]),
        ),
        migrations.DeleteModel(
            name='GenericOptions',
        ),
        migrations.AddField(
            model_name='registeredgroupsforactivity',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Group'),
        ),
        migrations.AddField(
            model_name='genericoption',
            name='genericId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Generic'),
        ),
        migrations.AddField(
            model_name='activityimageassigment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity'),
        ),
        migrations.AddField(
            model_name='activityassigment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity'),
        ),
        migrations.AddField(
            model_name='response',
            name='registeredGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2preview.RegisteredGroupsForActivity'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='response',
            name='activityId',
        ),
        migrations.RemoveField(
            model_name='response',
            name='groupId',
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('registeredGroup', 'criteria')]),
        ),
        migrations.AlterUniqueTogether(
            name='registeredgroupsforactivity',
            unique_together=set([('groupId', 'assigmentPk')]),
        ),
        migrations.AlterUniqueTogether(
            name='genericoption',
            unique_together=set([('genericId', 'optionNo')]),
        ),
    ]
