# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic',
            name='iId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor'),
            preserve_default=False,
        ),
    ]
