# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0002_auto_20171211_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastLogouted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
