# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0002_auto_20171102_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredgroupsforactivity',
            name='activityId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity'),
            preserve_default=False,
        ),
    ]
