# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0002_generic_iid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimageassigment',
            name='groupId',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
