# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0002_auto_20170910_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Course')),
                ('sId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Student')),
            ],
        ),
    ]
