# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0003_activityimageassigment_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
