# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-19 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0003_person_lastlogouted'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tasktimeinmin',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='department',
            field=models.CharField(default='CSE', max_length=5),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='office',
            field=models.CharField(default='1102', max_length=10),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='visitingHours',
            field=models.CharField(default='10AM-5PM', max_length=20),
        ),
    ]
