# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-19 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0004_auto_20180819_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='logincount',
            field=models.IntegerField(default=0),
        ),
    ]
