# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0004_auto_20170918_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
