# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-20 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0005_person_logincount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tasktimeinmin',
            field=models.IntegerField(),
        ),
    ]
