# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0005_auto_20170918_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupDetails',
            new_name='GroupDetail',
        ),
    ]
