# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0006_auto_20170930_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericOptions',
            new_name='GenericOption',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='imageURL',
            new_name='fileURL',
        ),
    ]
