# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0006_auto_20171208_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
