# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0007_auto_20171209_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityassigment',
            name='groupId',
            field=models.TextField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='activityimageassigment',
            name='groupId',
            field=models.TextField(blank=True, default='', max_length=30, null=True),
        ),
    ]
