# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0008_auto_20171001_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericoption',
            name='option',
            field=models.CharField(default='', max_length=100),
        ),
    ]
