# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0010_auto_20171001_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredGroupsForActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registeredgroupsforactivity',
            unique_together=set([('groupId', 'activityId')]),
        ),
    ]
