# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0011_auto_20171009_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='activityId',
        ),
        migrations.RemoveField(
            model_name='response',
            name='groupId',
        ),
        migrations.AddField(
            model_name='response',
            name='criteria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='p2preview.Criteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='registeredGroup',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='p2preview.RegisteredGroupsForActivity'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together=set([('rubricId', 'genericId')]),
        ),
    ]
