# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0013_auto_20171020_1314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('registeredGroup', 'criteria')]),
        ),
    ]
