# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0015_auto_20171021_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredgroupsforactivity',
            old_name='lastLogined',
            new_name='time',
        ),
    ]
