# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0016_auto_20171022_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='iId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2preview.Person'),
            preserve_default=False,
        ),
    ]
