# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0017_rubric_iid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='iId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Instrutor'),
        ),
    ]
