# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0019_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='p2preview/static/p2preview/files'),
        ),
    ]
