# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0021_activity_iid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='fileURL',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityassigment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity'),
        ),
    ]
