# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0022_auto_20171101_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='textOrImage',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generic',
            name='answer',
            field=models.IntegerField(blank=True),
        ),
    ]
