# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0024_activityassigment_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityassigment',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
