# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2preview', '0025_activityassigment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImageAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileURL', models.CharField(default='', max_length=5000)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2preview.Activity')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='activity',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.ImageField(upload_to='p2preview/static/p2preview/files'),
        ),
    ]
